[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "zqm-security-policy"
version = "0.1.0"
description = "ZQM-Computing security policy"
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "Alex Zelenski", email = "zqmcomputing@gmail.com"}
]
requires-python = ">=3.11"
dependencies = [
    "zqm-intel-platforms>=0.1.0",
]

[tool.setuptools.packages.find]
where = ["."]

[project.urls]
Homepage = "https://github.com/ZQM-Labs/zqm-security-policy"
Repository = "https://github.com/ZQM-Labs/zqm-security-policy.git"
